import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/Splitties/refreshVersions
 */
public object Libs {
    public const val activity_compose: String = "androidx.activity:activity-compose:_"

    public const val activity_ktx: String = "androidx.activity:activity-ktx:_"

    public const val benchmark_macro_junit4: String = "androidx.benchmark:benchmark-macro-junit4:_"

    public const val animation: String = "androidx.compose.animation:animation:_"

    public const val androidx_compose_compiler_compiler: String =
            "androidx.compose.compiler:compiler:_"

    public const val material3: String = "androidx.compose.material3:material3:_"

    public const val material3_window_size_class: String =
            "androidx.compose.material3:material3-window-size-class:_"

    public const val material_icons_extended: String =
            "androidx.compose.material:material-icons-extended:_"

    public const val ui: String = "androidx.compose.ui:ui:_"

    public const val ui_test_junit4: String = "androidx.compose.ui:ui-test-junit4:_"

    public const val ui_tooling: String = "androidx.compose.ui:ui-tooling:_"

    public const val ui_tooling_preview: String = "androidx.compose.ui:ui-tooling-preview:_"

    public const val core_ktx: String = "androidx.core:core-ktx:_"

    public const val viewbinding: String = "androidx.databinding:viewbinding:_"

    public const val fragment_ktx: String = "androidx.fragment:fragment-ktx:_"

    public const val fragment_testing: String = "androidx.fragment:fragment-testing:_"

    public const val lifecycle_runtime_ktx: String = "androidx.lifecycle:lifecycle-runtime-ktx:_"

    public const val lifecycle_runtime_testing: String =
            "androidx.lifecycle:lifecycle-runtime-testing:_"

    public const val lifecycle_viewmodel_compose: String =
            "androidx.lifecycle:lifecycle-viewmodel-compose:_"

    public const val lifecycle_viewmodel_ktx: String =
            "androidx.lifecycle:lifecycle-viewmodel-ktx:_"

    public const val navigation_compose: String = "androidx.navigation:navigation-compose:_"

    public const val navigation_fragment_ktx: String =
            "androidx.navigation:navigation-fragment-ktx:_"

    public const val navigation_ui_ktx: String = "androidx.navigation:navigation-ui-ktx:_"

    public const val profileinstaller: String = "androidx.profileinstaller:profileinstaller:_"

    public const val room_compiler: String = "androidx.room:room-compiler:_"

    public const val room_ktx: String = "androidx.room:room-ktx"

    public const val room_runtime: String = "androidx.room:room-runtime:_"

    public const val espresso_contrib: String = "androidx.test.espresso:espresso-contrib:_"

    public const val espresso_core: String = "androidx.test.espresso:espresso-core:_"

    public const val espresso_intents: String = "androidx.test.espresso:espresso-intents:_"

    public const val androidx_test_ext_junit: String = "androidx.test.ext:junit:_"

    public const val uiautomator: String = "androidx.test.uiautomator:uiautomator:_"

    public const val androidx_test_core: String = "androidx.test:core:_"

    public const val androidx_test_rules: String = "androidx.test:rules:_"

    public const val androidx_test_runner: String = "androidx.test:runner:_"

    public const val control_core: String = "at.florianschuster.control:control-core:_"

    public const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    public const val material: String = "com.google.android.material:material:_"

    public const val gson: String = "com.google.code.gson:gson:_"

    public const val threetenabp: String = "com.jakewharton.threetenabp:threetenabp:_"

    public const val timber: String = "com.jakewharton.timber:timber:_"

    public const val ktlint_reporter_baseline: String =
            "com.pinterest.ktlint:ktlint-reporter-baseline:_"

    public const val ktlint_ruleset_standard: String =
            "com.pinterest.ktlint:ktlint-ruleset-standard:_"

    public const val ktlint: String = "com.pinterest:ktlint:_"

    public const val leakcanary_android: String = "com.squareup.leakcanary:leakcanary-android:_"

    public const val leakcanary_object_watcher_android: String =
            "com.squareup.leakcanary:leakcanary-object-watcher-android:_"

    public const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:_"

    public const val okhttp: String = "com.squareup.okhttp3:okhttp:_"

    public const val converter_gson: String = "com.squareup.retrofit2:converter-gson:_"

    public const val retrofit: String = "com.squareup.retrofit2:retrofit:_"

    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val coil_compose: String = "io.coil-kt:coil-compose:_"

    public const val koin_android: String = "io.insert-koin:koin-android:_"

    public const val koin_androidx_compose: String = "io.insert-koin:koin-androidx-compose:_"

    public const val koin_core: String = "io.insert-koin:koin-core:_"

    public const val koin_test: String = "io.insert-koin:koin-test:_"

    public const val mockk: String = "io.mockk:mockk:_"

    public const val junit_junit: String = "junit:junit:_"

    public const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:_"

    public const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:_"

    public const val kotlin_parcelize_compiler: String =
            "org.jetbrains.kotlin:kotlin-parcelize-compiler:_"

    public const val kotlin_parcelize_runtime: String =
            "org.jetbrains.kotlin:kotlin-parcelize-runtime:_"

    public const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:_"

    public const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:_"

    public const val kotlin_test: String = "org.jetbrains.kotlin:kotlin-test:_"

    public const val kotlinx_coroutines_core: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core:_"

    public const val kotlinx_coroutines_test: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-test:_"

    public const val org_jlleitschuh_gradle_ktlint_gradle_plugin: String =
            "org.jlleitschuh.gradle.ktlint:org.jlleitschuh.gradle.ktlint.gradle.plugin:_"
}
